### ISSUE TITLE
Acidisland Addon - Respiration enchantment affect acid damage

### ISSUE THREAD

**Issue by Poslovitch** [BentoBoxWorld/AcidIsland#8]
_From @TheWranger on September 1, 2018 1:48_

**Is your feature request related to a problem? Please describe.**
Currently, the only way to block acid damage is to either a full set of armor (a bit overpowered) or to drink a water breathing potion.

**Describe the solution you'd like**
I think that the Respiration enchantment should reduce acid damage by a configurable amount, increasing with each enchantment level it has. I think this is better in terms of player equipment progression (instead of just negating acid damage altogether if they have a full set of armor).

**Describe alternatives you've considered**
I originally considered depth strider to be the enchantment to do this, however I think respiration is better because of how it increases underwater breathing time, similar to how the water breathing potion does.

**Additional context**
Nothing else.

_Copied from original issue: BentoBoxWorld/bentobox#255_

**Comment by Poslovitch** [comment]
_From @tastybento on September 1, 2018 3:46_

I'll look into it. BTW, the more armor you have, the less the damage. Diamond armor has the best protection. Also, you wear a turtle helmet there is protection.

**Comment by TheWranger** [comment]
@tastybento Has the dynamic acid damage per armor already been implemented or is that something that is planned?
Can only see
```
    protection:
      # If player wears a helmet then they will not suffer from acid rain
      helmet: false
      # If player wears any set of full armor, they will not suffer from acid damage
      full-armor: false
```
in the config at the moment.
